name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-package:
    name: Test Package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v2.0.0

      - name: Install Dependencies
        run: pnpm install

      - name: Test Package
        run: pnpm test

  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v6.0.3
        with:
          path: setup-yarn-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Create Sample Package
        shell: bash
        run: |
          cat <<'EOF' > package.json
          {
            "name": "sample-package",
            "version": "0.0.0",
            "packageManager": "yarn@4.0.2",
            "dependencies": {
              "picocolors": "^1.1.1"
            }
          }
          EOF

      - name: Setup Yarn
        uses: ./setup-yarn-action

      - name: Build Package
        run: yarn pack

  test-action-with-specific-version:
    name: Test Action With Specific Version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v6.0.3
        with:
          path: setup-yarn-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Create Sample Package
        shell: bash
        run: |
          cat <<'EOF' > package.json
          {
            "name": "sample-package",
            "version": "0.0.0",
            "dependencies": {
              "picocolors": "^1.1.1"
            }
          }
          EOF

      - name: Setup Yarn
        uses: ./setup-yarn-action
        with:
          version: 4.0.2

      - name: Check Version
        shell: bash
        run: test $(yarn --version) == 4.0.2

      - name: Build Package
        run: yarn pack

  test-action-without-cache:
    name: Test Action Without Cache
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v6.0.3
        with:
          path: setup-yarn-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Create Sample Package
        shell: bash
        run: |
          cat <<'EOF' > package.json
          {
            "name": "sample-package",
            "version": "0.0.0",
            "packageManager": "yarn@4.0.2",
            "dependencies": {
              "picocolors": "^1.1.1"
            }
          }
          EOF

      - name: Setup Yarn
        uses: ./setup-yarn-action
        with:
          cache: false

      - name: Build Package
        run: yarn pack

  test-action-with-yarn-local-cache:
    name: Test Action With Yarn Local Cache
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Action
        uses: actions/checkout@v6.0.3
        with:
          path: setup-yarn-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Create Sample Package
        shell: bash
        run: |
          cat <<'EOF' > package.json
          {
            "name": "sample-package",
            "version": "0.0.0",
            "packageManager": "yarn@4.0.2",
            "dependencies": {
              "picocolors": "^1.1.1"
            }
          }
          EOF

      - name: Disable Yarn Global Cache
        run: |
          corepack enable yarn
          yarn config set enableGlobalCache false

      - name: Setup Yarn
        uses: ./setup-yarn-action

      - name: Build Package
        run: yarn pack
